name: FTP Deploy

on:
  push:
    branches:
      - main  # Or use 'master' if your branch is named master

jobs:
  ftp-deploy:
    name: 📂 Upload to FTP
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📁 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}
